repos:
  # Ruff: lint + import sort + pyupgrade + formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff            # lint (uses pyproject.toml)
      - id: ruff-format     # formatter (uses pyproject.toml)

  # Small hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
